services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bionicpro-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_PORT: 8080
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      ldap:
        condition: service_started
    networks:
      - bionicpro-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8002
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
      REACT_APP_AUTH_URL: http://localhost:8001
    depends_on:
      - bionicpro-auth
    networks:
      - bionicpro-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bionicpro-network

  bionicpro-auth:
    build: ./bionicpro-auth
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=reports-realm
      - KEYCLOAK_CLIENT_ID=reports-frontend
    depends_on:
      - redis
      - keycloak
    networks:
      - bionicpro-network

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "BionicPRO"
      LDAP_DOMAIN: "bionicpro.local"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_LOG_LEVEL: "256"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      # Добавьте эти переменные
      LDAP_ADDITIONAL_SCHEMAS: "cosine"
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"
    networks:
      - bionicpro-network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    user: root
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DB: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    security_opt:
      - seccomp:unconfined
    networks:
      - bionicpro-network

  airflow-db:
    image: postgres:13
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./airflow-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    build: ./airflow
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - airflow-db
    networks:
      - bionicpro-network

  airflow-scheduler:
    build: ./airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
    command: airflow scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      airflow-db:
        condition: service_healthy
    networks:
      - bionicpro-network

  report-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    volumes:
      - ./report-service/app.py:/app/main.py
    ports:
      - "8002:80"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
    networks:
      - bionicpro-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    ports:
      - "9002:9000"
      - "9003:9001"
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx-cdn:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/var/cache/nginx
    ports:
      - "8084:80"
    depends_on:
      - minio
    networks:
      - bionicpro-network

networks:
  bionicpro-network:
    driver: bridge

volumes:
  redis-data: