FROM python:3.11-slim

WORKDIR /app

# Устанавливаем только необходимые пакеты
RUN pip install --no-cache-dir fastapi uvicorn httpx

COPY app.py .

EXPOSE 8002

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8002"]